import sys
import os
import glob
import cv2
import numpy as np
from tqdm import tqdm

# Add project root to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.config import CONFIG
from src.inference import predict
from src.utils import mask2rle, calculate_iou, calculate_dice, calculate_precision_recall, load_model
from src.visualize import visualize_results_stratified


def run_evaluation(classifier, seg_model, config, device, test_dir, output_file, threshold):
    """
    Run evaluation: predict once, calculate metrics, generate submission.
    """
    img_paths = sorted(glob.glob(str(test_dir / 'images' / '*.jpg')))
    mask_paths = sorted(glob.glob(str(test_dir / 'masks' / '*.jpg')))
    
    if not img_paths or not mask_paths:
        raise RuntimeError("No test data found!")
    
    print(f"\nEvaluating on {len(img_paths)} images (Threshold: {threshold:.4f})...")
    
    # Storage for metrics
    ious, dices, precisions, recalls = [], [], [], []
    results = []
    # Open submission file
    with open(output_file, 'w') as f:
        f.write('file,crack\n')
        
        # Single pass through all images
        for img_path, mask_path in tqdm(zip(img_paths, mask_paths), total=len(img_paths), desc="Processing"):
            # Get filename for submission
            img_id = os.path.basename(img_path)
            
            # === RUN PREDICTION ONCE ===
            result = predict(img_path, classifier, seg_model, config, device, seg_threshold=threshold)
            pred_mask = result['mask']
            
            # === METRICS ===
            true_mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
            true_binary = (true_mask > 127).astype(np.uint8)
            
            iou = calculate_iou(pred_mask, true_binary)
            dice = calculate_dice(pred_mask, true_binary)
            p, r = calculate_precision_recall(pred_mask, true_binary)
            
            ious.append(iou)
            dices.append(dice)
            precisions.append(p)
            recalls.append(r)

            results.append({
                'img_path': img_path,
                'mask_path': mask_path,
                'pred': pred_mask,
                'dice': dice
            })

            # === SUBMISSION ===
            if not result['has_crack'] or pred_mask.sum() == 0:
                f.write(f'{img_id},\n')
            else:
                rle = mask2rle(pred_mask)
                f.write(f'{img_id},{rle}\n')
    
    print("Test set metrics:")
    print(f"  Mean IoU:       {np.mean(ious):.4f}")
    print(f"  Mean Dice:      {np.mean(dices):.4f}")
    print(f"  Precision:      {np.mean(precisions):.4f}")
    print(f"  Recall:         {np.mean(recalls):.4f}")
    print(f"Submission saved to {output_file}")

    visualize_results_stratified(
        results=results,
        save_path='visualization_stratified.png'
    )
from src.models import UNetLight, GradCAMPlusPlus
import torch
if __name__ == "__main__":
    # Debug threshold - just for quick testing, should be generated by Otsu
    DEBUG_THRESHOLD = 0.1373
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    
    # Load models
    classifier = GradCAMPlusPlus().to(device)
    seg_model = UNetLight().to(device)
    
    load_model(classifier, CONFIG["cls_model_path"], device)
    load_model(seg_model, CONFIG["seg_model_path"], device)
    
    classifier.eval()
    seg_model.eval()
    
    test_dir = CONFIG["root_dir"] / 'test'
    output_file = CONFIG["submission_file"]
    
    run_evaluation(
        classifier=classifier,
        seg_model=seg_model,
        config=CONFIG,
        device=device,
        test_dir=test_dir,
        output_file=output_file,
        threshold=DEBUG_THRESHOLD
    )